services:
  api:
    build: .
    container_name: spring-boot-app
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8081:8081"
    networks:
      - app-network
    volumes:
      - .env:/app/.env

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      retries: 5
      timeout: 5s
    networks:
      - app-network

networks:
  app-network:
